"""svg

Revision ID: 2d0b5767a0b8
Revises: 1c766a5f4479
Create Date: 2024-12-09 23:01:32.202578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0b5767a0b8'
down_revision = '1c766a5f4479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('telegram_link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('favorite_sport_club', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_sport_club')
        batch_op.drop_column('bio')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('telegram_link')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
