"""Add course_student table

Revision ID: 2e83e045148c
Revises: 4f3ce7cf1811
Create Date: 2024-12-04 13:21:45.481550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e83e045148c'
down_revision = '4f3ce7cf1811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('course_student_student_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('course_student_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_course_student_student_id', 'students', ['student_id'], ['id'],
                                    ondelete='CASCADE')
        batch_op.create_foreign_key('fk_course_student_course_id', 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_student_student_id', type_='foreignkey')
        batch_op.drop_constraint('fk_course_student_course_id', type_='foreignkey')
        batch_op.create_foreign_key('course_student_course_id_fkey', 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key('course_student_student_id_fkey', 'students', ['student_id'], ['id'])
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
