"""empty message

Revision ID: 56715e519a91
Revises: 2e83e045148c
Create Date: 2024-12-06 00:12:46.559948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56715e519a91'
down_revision = '2e83e045148c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('unique_course_student', type_='unique')
        batch_op.drop_constraint('course_student_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('course_student_student_id_fkey', 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('unique_course_student', ['course_id', 'student_id'])
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
