"""Make fields nullable

Revision ID: 70a4d15700cd
Revises: 07f1181a197b
Create Date: 2024-11-25 20:48:40.532642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a4d15700cd'
down_revision = '07f1181a197b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('num_of_course',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('university',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('group',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('university',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('num_of_course',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
