"""svg

Revision ID: 7a69c6f0d70e
Revises: e3b886c31492
Create Date: 2024-12-06 01:26:05.684408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a69c6f0d70e'
down_revision = 'e3b886c31492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_student', 'users', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
