"""Added nickname, date_of_birth, accept_policy to users

Revision ID: 7c3193a41a0b
Revises: 70a4d15700cd
Create Date: 2024-11-25 21:43:53.232309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3193a41a0b'
down_revision = '70a4d15700cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('accept_policy', sa.Boolean(), nullable=False))
        batch_op.alter_column('num_of_course',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('university',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('group',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('university',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('num_of_course',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('accept_policy')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
