"""Refactored student logic to use users table

Revision ID: dcafc59a6353
Revises: 7fe6a16e05b2
Create Date: 2024-12-08 16:48:03.625674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcafc59a6353'
down_revision = '7fe6a16e05b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.drop_constraint('course_student_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('course_student_student_id_fkey', 'students', ['student_id'], ['id'], ondelete='CASCADE')

    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('university', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='students_pkey'),
    sa.UniqueConstraint('email', name='students_email_key')
    )
    # ### end Alembic commands ###
