"""svg

Revision ID: e3b886c31492
Revises: 56715e519a91
Create Date: 2024-12-06 01:04:10.021303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b886c31492'
down_revision = '56715e519a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_materials', schema=None) as batch_op:
        batch_op.alter_column('need_to_delete',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_materials', schema=None) as batch_op:
        batch_op.alter_column('need_to_delete',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
