"""empty message

Revision ID: f19919f95fbb
Revises: 7e308304bb60
Create Date: 2024-12-08 15:33:07.787622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19919f95fbb'
down_revision = '7e308304bb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_course', type_='foreignkey')
        batch_op.drop_constraint('course_student_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('course_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('course_student_student_id_fkey', 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_course', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
