"""svg

Revision ID: fae5a9584c35
Revises: f7a5b4e164a4
Create Date: 2024-11-30 16:04:25.942573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae5a9584c35'
down_revision = 'f7a5b4e164a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need_to_delete', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_materials', schema=None) as batch_op:
        batch_op.drop_column('need_to_delete')

    # ### end Alembic commands ###
